### PR TITLE
Update list_uBlacklist.txt with better Amazon URL catching

### PR DESCRIPTION
**Pull request by xor50**
1) catch all Amazon TLDs
2) because Amazon URLs are weird you can actually have whatever text you want before the dp/[code] so we need to catch all of those. The dp/[code] is the only part of the URL that defines the product.

### CODE REVIEW

**Comment by laylavish** [comment]
Weirdly, this isn't working for me.

**Comment by xor50** [comment]
I haven't tested the change in the filter, I just assume * would work "normally" as wild card in those filter lists. Maybe wild cards work differently?

But you can 100% check the URLs for yourself. Let's use something harmless, maybe some toy bear:

1) https://www.amazon.com/this_is_a_toybear/dp/B0BYSN5H82/
2) https://www.amazon.de/somethingelseherebutthesameproduct/dp/B0BYSN5H82/

Not that it's the exact same but the difference in TLD and the part before /dp/[code]

**Comment by laylavish** [comment]
So, uBlacklist does not support wildcard match patterns for top level domains, but fortunately you can use regex. This one I made seems to work well.

```
 /amazon.+\/.+\/dp\/B0CVTYD34P/
```

You can use this template for these changes (replace `B0CVTYD34P` with each product name you want matched), then I'll merge (or I can just do a good ol'e commit).

**Comment by laylavish** [comment]
nevermind, i just committed my regex version in main, so this should catch all amazon urls

**Pull request closed without merging**
